In [44]:
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [45]:
vec1 > vec2

array([False, False,  True, False])

In [46]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [ ]:
length = np.linalg.norm(vec)
length

In [ ]:
distance = np.linalg.norm(vec1-vec2)
distance

In [47]:
scalar_product = np.dot(vec1, vec2)
scalar_product

105.7

In [48]:
print(vec.min())

print(vec.max())

print(vec.mean())

5
89
30.142857142857142


Random

In [ ]:
np.random.rand()

In [ ]:
#np.random.rand() * 100

np.random.rand(5,5)

In [ ]:
shape = (3,4)
np.random.sample(shape)

In [ ]:
np.random.uniform(-30,50, size=5)

In [50]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]

shuffled = np.random.permutation(playlist)
print(playlist)
print(shuffled)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Deep Purple' 'Pink Floyd' 'The Beatles' 'ACDC']


In [49]:

choice1 = np.random.choice(playlist, size=2, replace=False)
print(choice1)

['Pink Floyd' 'Deep Purple']


In [51]:
import pandas as pd
pd.__version__
print(pd.__name__)

pandas


In [ ]:
from tkinter import *

root = Tk()
root.title("Моя первая графическая программа на Python")
root.geometry("400x250")
root.resizable(width=False, height=False)

root.mainloop()