In [44]:
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [45]:
vec1 > vec2

array([False, False,  True, False])

In [46]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [ ]:
length = np.linalg.norm(vec)
length

In [ ]:
distance = np.linalg.norm(vec1-vec2)
distance

In [47]:
scalar_product = np.dot(vec1, vec2)
scalar_product

105.7

In [48]:
print(vec.min())

print(vec.max())

print(vec.mean())

5
89
30.142857142857142


Random

In [ ]:
np.random.rand()

In [ ]:
#np.random.rand() * 100

np.random.rand(5,5)

In [ ]:
shape = (3,4)
np.random.sample(shape)

In [ ]:
np.random.uniform(-30,50, size=5)

In [50]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]

shuffled = np.random.permutation(playlist)
print(playlist)
print(shuffled)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Deep Purple' 'Pink Floyd' 'The Beatles' 'ACDC']


In [49]:

choice1 = np.random.choice(playlist, size=2, replace=False)
print(choice1)

['Pink Floyd' 'Deep Purple']


In [51]:
import pandas as pd
pd.__version__
print(pd.__name__)

pandas


In [ ]:
from tkinter import *

root = Tk()
root.title("Моя первая графическая программа на Python")
root.geometry("400x250")
root.resizable(width=False, height=False)

root.mainloop()

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline

Pandas

In [4]:
import pandas as pd
countries_df = pd.DataFrame(
    data = [
        ['Англия', 56.29, 133396],
        ['Канада', 38.05, 9984670],
        ['США', 322.28, 9826630],
        ['Россия', 146.24, 17125191],
        ['Украина', 45.5, 603628],
        ['Беларусь', 9.5, 207600],
        ['Казахстан', 17.04, 2724902]
    ],
    columns= ['country', 'population', 'area'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
)
display(countries_df)

country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

In [5]:
countries_df.loc['UK', 'area']

np.int64(133396)

In [8]:
countries_df.loc['RU', ['population', 'area']]

population      146.24
area          17125191
Name: RU, dtype: object

In [7]:
countries_df.iloc[4:8, 1:3]

countries_df.loc[['UA', 'BY', 'KZ'],['population', 'area']]

population     area
UA       45.50   603628
BY        9.50   207600
KZ       17.04  2724902

In [9]:
#сохранить файл
countries_df.to_csv('data/countries.csv', index=False, sep=';')